# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
#    paths-ignore:
#      - '**.adoc'
#      - '**.md'
  pull_request:
    branches: [ "main" ]
#    paths-ignore:
#      - '**.adoc'
#      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ '21', '22' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
        cache: maven

    # Skip the build if the commit message contains [ci skip], [skip ci], [no ci], [ci skip-build], [skip-build ci], [no-build ci], [ci ignore], [ignore ci], [doc:] or [docs:] and keep the information to the next step verify if it should be executed
    - name: Skip CI if necessary
      id: skip-ci
      run: echo "Checking commit message for [ci skip], [skip ci], [no ci], [ci skip-build], [skip-build ci], [no-build ci], [ci ignore], [ignore ci], [doc:] or [docs:]"
      continue-on-error: true

    - name: Build with Maven using JDK ${{ matrix.java }}
      if: ${{ !contains(github.event.head_commit.message, '[ci skip]') 
          && !contains(github.event.head_commit.message, '[skip ci]') 
          && !contains(github.event.head_commit.message, '[no ci]') 
          && !contains(github.event.head_commit.message, '[ci skip-build]') 
          && !contains(github.event.head_commit.message, '[skip-build ci]') 
          && !contains(github.event.head_commit.message, '[no-build ci]') 
          && !contains(github.event.head_commit.message, '[ci ignore]') 
          && !contains(github.event.head_commit.message, '[ignore ci]') 
          && !contains(github.event.head_commit.message, '[doc:]') 
          && !contains(github.event.head_commit.message, '[docs:]') }}
      run: ./mvnw verify --file pom.xml
